name: filatelia
description: Álbum de sellos españoles en pesetas
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^8.0.2
  path_provider: ^2.1.1
  intl: ^0.20.2
  flutter_animate: ^4.3.0
  window_manager: ^0.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
